{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-10 01:12:42","url":"/review"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-10 01:26:57","url":"/review"}
{"code":"model_not_found","error":{"code":"model_not_found","message":"The model `gpt-4` does not exist or you do not have access to it.","param":null,"type":"invalid_request_error"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"95ca6495cb1a54a8-DEL","connection":"keep-alive","content-encoding":"gzip","content-type":"application/json; charset=utf-8","date":"Wed, 09 Jul 2025 19:57:53 GMT","server":"cloudflare","set-cookie":"__cf_bm=4pdQHksdhklQNzBXpQSR_Noy9lpIfXhk6TNc1SQHoCA-1752091073-1.0.1.1-_Vi_6v2k3iHH7zztlz1NwX9SAIyY.7EOMNL5Y5QYJkAEHqLASUb_gAgkhNn.O4K9YQ6MlWfCLvwpRzzN4zakGzLYQYtKLb3hKlp0E0QjyUM; path=/; expires=Wed, 09-Jul-25 20:27:53 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=UoUDLuCc87ZLNsEB5iEcBn7d_xcRwnINYva8aynfbL8-1752091073635-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","transfer-encoding":"chunked","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_58f7e89ded5fde32803dac48c0fbd5dc"},"level":"error","message":"AI review error: 404 The model `gpt-4` does not exist or you do not have access to it.","param":null,"request_id":"req_58f7e89ded5fde32803dac48c0fbd5dc","service":"ai-service","stack":"Error: 404 The model `gpt-4` does not exist or you do not have access to it.\n    at APIError.generate (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\error.js:54:20)\n    at OpenAI.makeStatusError (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\core.js:302:33)\n    at OpenAI.makeRequest (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\core.js:346:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:17:24)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:28","status":404,"timestamp":"2025-07-10 01:27:53","type":"invalid_request_error"}
{"level":"error","message":"Review error: Failed to generate AI review","service":"ai-service","stack":"Error: Failed to generate AI review\n    at AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:38:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:28","timestamp":"2025-07-10 01:27:53"}
{"code":"insufficient_quota","error":{"code":"insufficient_quota","message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"type":"insufficient_quota"},"headers":{"alt-svc":"h3=\":443\"; ma=86400","cf-cache-status":"DYNAMIC","cf-ray":"95ca76724aa7e502-DEL","connection":"keep-alive","content-length":"337","content-type":"application/json; charset=utf-8","date":"Wed, 09 Jul 2025 20:10:05 GMT","server":"cloudflare","set-cookie":"__cf_bm=lnqEUatohlVGH2ZlaNRd6UHdatJDdHt3irE9BSpmNgY-1752091805-1.0.1.1-PP_WmaMAwSXk7MDWMgc0pMvjwbLwRvyspWJ88er7Ogz8FSG44PUuNeahby27J1oiQmicKfSc9TcbSAz7KLfMGFdSHLF77DJQUYuBbx6aLHk; path=/; expires=Wed, 09-Jul-25 20:40:05 GMT; domain=.api.openai.com; HttpOnly; Secure; SameSite=None, _cfuvid=aFoHC.tjTCkIAP_DsxNcWU_3mXVt5NQMZij.ccOS6Rs-1752091805132-0.0.1.1-604800000; path=/; domain=.api.openai.com; HttpOnly; Secure; SameSite=None","strict-transport-security":"max-age=31536000; includeSubDomains; preload","vary":"Origin","x-content-type-options":"nosniff","x-request-id":"req_4bb561e797d05759e2d1df3ad54e894a"},"level":"error","message":"AI review error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","param":null,"request_id":"req_4bb561e797d05759e2d1df3ad54e894a","service":"ai-service","stack":"Error: 429 You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.\n    at APIError.generate (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\error.js:63:20)\n    at OpenAI.makeStatusError (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\core.js:302:33)\n    at OpenAI.makeRequest (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\openai\\core.js:346:30)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:17:24)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:28","status":429,"timestamp":"2025-07-10 01:40:04","type":"insufficient_quota"}
{"level":"error","message":"Review error: Failed to generate AI review","service":"ai-service","stack":"Error: Failed to generate AI review\n    at AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:38:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:28","timestamp":"2025-07-10 01:40:04"}
{"level":"error","message":"Review error: aiService.reviewCode is not a function","service":"ai-service","stack":"TypeError: aiService.reviewCode is not a function\n    at C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:44\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-07-10 13:57:11"}
{"level":"error","message":"Review error: aiService.reviewCode is not a function","service":"ai-service","stack":"TypeError: aiService.reviewCode is not a function\n    at C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:44\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-07-10 13:57:43"}
{"level":"error","message":"AI review error: ai.getGenerativeModel is not a function","service":"ai-service","stack":"TypeError: ai.getGenerativeModel is not a function\n    at AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:175:24)\n    at C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:44\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-07-10 14:06:25"}
{"level":"error","message":"Review error: Failed to generate AI review","service":"ai-service","stack":"Error: Failed to generate AI review\n    at AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:183:13)\n    at C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:38:44\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)","timestamp":"2025-07-10 14:06:25"}
{"level":"error","message":"AI review error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [503 Service Unavailable] The model is overloaded. Please try again later.","service":"ai-service","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [503 Service Unavailable] The model is overloaded. Please try again later.\n    at handleResponseNotOk (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:15:22)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:43:28","status":503,"statusText":"Service Unavailable","timestamp":"2025-07-11 22:42:56"}
{"body":{},"error":"Expected ',' or '}' after property value in JSON at position 43 (line 1 column 44)","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"SyntaxError: Expected ',' or '}' after property value in JSON at position 43 (line 1 column 44)\n    at JSON.parse (<anonymous>)\n    at parse (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\body-parser\\lib\\types\\json.js:92:19)\n    at C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\body-parser\\lib\\read.js:128:18\n    at AsyncResource.runInAsyncScope (node:async_hooks:214:14)\n    at invokeCallback (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:238:16)\n    at done (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:227:7)\n    at IncomingMessage.onEnd (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:287:7)\n    at IncomingMessage.emit (node:events:518:28)\n    at endReadableNT (node:internal/streams/readable:1698:12)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)","timestamp":"2025-07-11 22:54:07","url":"/review"}
{"level":"error","message":"AI review error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [503 Service Unavailable] The model is overloaded. Please try again later.","service":"ai-service","stack":"Error: [GoogleGenerativeAI Error]: Error fetching from https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent: [503 Service Unavailable] The model is overloaded. Please try again later.\n    at handleResponseNotOk (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:434:11)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async makeRequest (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:403:9)\n    at async generateContent (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\@google\\generative-ai\\dist\\index.js:867:22)\n    at async AIService.reviewCode (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\services\\aiService.js:15:22)\n    at async C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\src\\routes\\review.js:43:28","status":503,"statusText":"Service Unavailable","timestamp":"2025-07-11 22:55:20"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-11 23:02:54","url":"/review"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-11 23:09:18","url":"/review"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-11 23:14:51","url":"/review"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-11 23:16:28","url":"/review"}
{"body":{},"error":"request aborted","ip":"::1","level":"error","message":"AI Service Error:","method":"POST","service":"ai-service","stack":"BadRequestError: request aborted\n    at IncomingMessage.onAborted (C:\\Users\\kesha\\OneDrive\\Desktop\\Projects\\Code Reviewer\\ai-service\\node_modules\\raw-body\\index.js:245:10)\n    at IncomingMessage.emit (node:events:518:28)\n    at IncomingMessage._destroy (node:_http_incoming:221:10)\n    at _destroy (node:internal/streams/destroy:122:10)\n    at IncomingMessage.destroy (node:internal/streams/destroy:84:5)\n    at abortIncoming (node:_http_server:809:9)\n    at socketOnClose (node:_http_server:803:3)\n    at Socket.emit (node:events:530:35)\n    at TCP.<anonymous> (node:net:351:12)","timestamp":"2025-07-11 23:19:30","url":"/review"}
